version: '3'
services:
  ww_exporter:
    build: .
    ports:
    - 3001:80
    volumes:
    - .:/app
    extra_hosts:
      - engines:172.23.0.3
    networks:
      - whaleblazer_www

networks:
  whaleblazer_www:
    external: true
