name: Build docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages & AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: Set docker image vars
        run: |
          echo "registry=docker.pkg.github.com" >> $GITHUB_ENV
          echo "repository=${{ github.repository }}" >> $GITHUB_ENV
          echo "gh_image_name=ww_exporter" >> $GITHUB_ENV
          echo "ecr_image_name=ww_exporter" >> $GITHUB_ENV
      - if: github.ref == 'refs/heads/master'
        run: |
          echo "image_tag=latest" >> $GITHUB_ENV
      - if: github.ref == 'refs/heads/live'
        run: |
          echo "image_tag=live" >> $GITHUB_ENV

      - name: Push to GitHub Packages
        uses: weavingwebs/ww-docker-build-action@1.0.3
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
          registry: ${{ env.registry }}
          repository: "${{ env.repository }}/${{ env.gh_image_name }}:${{ env.image_tag }}"
          push: "1"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WHALEBLAZER_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WHALEBLAZER_ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push to ECR
        env:
          IMAGE: "${{ env.registry }}/${{ env.repository }}/${{ env.gh_image_name }}:${{ env.image_tag }}"
          ECR_IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ env.ecr_image_name }}:${{ env.image_tag }}"
        run: |
          docker tag "$IMAGE" "$ECR_IMAGE"
          docker push "$ECR_IMAGE"
